resources:
- name: pcf-pipelines-maestro
  type: git
  source:
   uri: {{maestro_project_url}}
   private_key: {{git_maestro_private_key}}

jobs:
- name: destroy-maestro-concourse-teams
  plan:
  - get: pcf-pipelines-maestro
    # trigger: true
  - task: destroy-maestro-teams
    file: ./pcf-pipelines-maestro/tasks/utils/teams-demolition/task.yml
